export default {
  id: "how-redis-talks-resp-protocol",
  title: "How Redis Talks: The RESP Protocol",
  category: "Systems",
  series: { id: "building-redis-java", part: 1 },
  tag: "Systems · Protocol Design",
  date: "May 2026",
  readTime: "13 min read",
  excerpt:
    "Exploring the Redis Serialization Protocol (RESP) — the byte-level wire format that makes Redis compatible with clients like redis-cli, Jedis, and Lettuce, and the streaming parsing challenges of implementing it correctly.",
  content: [
    { type: "p", text: "Welcome to the first article in the series: Building a Redis-Compatible Server from Scratch in Java. In this series, I'll explain the implementation, design choices, and everything related to the redis-java project that you can check out on GitHub." },
    { type: "p", text: "Before building a Redis server that stores keys, expires values, or replicates writes, we need a protocol — a language that clients and servers mutually understand. For true Redis compatibility, that protocol is RESP: the Redis Serialization Protocol." },
    { type: "h2", text: "Why RESP? Why not JSON or HTTP?" },
    { type: "p", text: "This is a valid question. Redis was designed in 2009, when JSON was already well-established and HTTP was ubiquitous. Why invent a completely new protocol at all?" },
    { type: "p", text: "The answer is simple: neither JSON nor HTTP is well-suited to the access pattern of a key-value store. JSON is designed for human readability and schema flexibility — properties that don't matter in a cache protocol. You don't need readable bytes. You need a format that is extremely fast to parse, produces low overhead per command, and maps directly to a small set of response types: strings, integers, errors, arrays, and nothing." },
    { type: "p", text: "HTTP carries significant framing overhead. Every request includes a method, path, headers, and body separators. For a workload where the average command is GET key (around 10 bytes), HTTP headers dwarf the actual payload. Worse, HTTP is inherently request-response — one at a time per connection — which conflicts directly with pipelining." },
    { type: "p", text: "RESP makes opposite tradeoffs: binary-safe, minimal, and streaming-friendly. A GET command is expressed in around 20 bytes. A bulk string response carries its length prefix rather than a delimiter, meaning the parser never scans the entire content—it just skips to the end using the prefix. Every design decision in RESP optimizes for throughput and simplicity over a persistent connection." },
    { type: "h2", text: "Five Types: The Complete Wire Format" },
    { type: "p", text: "RESP defines five data types. Every message on the wire is one of these, and the first byte identifies the type unambiguously." },
    { type: "h2", text: "Simple String" },
    { type: "code", lang: "text", text: "+OK\\r\\n\n+PONG\\r\\n" },
    { type: "p", text: "A '+' prefix followed by text and terminated with \\r\\n. Used for short server responses where the content is known to be safe ASCII with no embedded newlines. SET returns +OK\\r\\n. PING returns +PONG\\r\\n." },
    { type: "p", text: "Critical caveat: Simple strings are not binary-safe. If content contains \\r or \\n, the parser will misidentify the end of the message." },
    { type: "h2", text: "Error" },
    { type: "code", lang: "text", text: "-ERR unknown command 'foo'\\r\\n\n-WRONGTYPE Operation against a key holding the wrong kind of value\\r\\n\n-READONLY You can't write against a read only replica\\r\\n" },
    { type: "p", text: "A '-' prefix followed by an error message. The first word is conventionally the error class (ERR, WRONGTYPE, READONLY). Client libraries use the error class to decide how to handle failures: retry, surface to caller, or treat as fatal." },
    { type: "p", text: "This matters for compatibility. The -READONLY error that replicas return is a specific string that Jedis and Lettuce know to handle. Return the wrong error string and the client library may behave incorrectly." },
    { type: "h2", text: "Integer" },
    { type: "code", lang: "text", text: ":1\\r\\n\n:0\\r\\n\n:42\\r\\n" },
    { type: "p", text: "A ':' prefix followed by a signed 64-bit integer and \\r\\n. Used for numeric results: return value of INCR, LLEN, TTL, whether SETNX succeeded. Integers in RESP are never floating-point. INCRBYFLOAT returns a Bulk String instead." },
    { type: "h2", text: "Bulk String" },
    { type: "code", lang: "text", text: "$7\\r\\n\nmyvalue\\r\\n" },
    { type: "p", text: "The most important type. A '$' prefix, then the byte length of content, then \\r\\n, then the content itself, then \\r\\n again." },
    { type: "p", text: "The length prefix is what makes Bulk Strings binary-safe. The parser reads exactly the declared number of bytes—it does not scan for a delimiter. Content can contain anything: null bytes, newlines, arbitrary binary data. This is how Redis stores serialized protobuf, compressed blobs, or raw binary alongside plain text in the same protocol." },
    { type: "p", text: "A length of -1 is the null bulk string (nil). GET on a non-existent key returns $-1\\r\\n. A length of 0 is the empty string, different from nil: $0\\r\\n\\r\\n is a valid value, $-1\\r\\n means the key does not exist." },
    { type: "h2", text: "Array" },
    { type: "code", lang: "text", text: "*3\\r\\n\n$3\\r\\n\nSET\\r\\n\n$5\\r\\n\nmykey\\r\\n\n$7\\r\\n\nmyvalue\\r\\n" },
    { type: "p", text: "A '*' prefix, then the number of elements, then each element encoded in its own RESP type. Arrays can contain any mixture of types, including nested arrays." },
    { type: "p", text: "This is how every client sends commands to the server. SET mykey myvalue is encoded as an array of three bulk strings: SET, mykey, myvalue. The server receives the *3\\r\\n header, reads three bulk strings, assembles them into a command, and dispatches." },
    { type: "p", text: "A count of -1 is the null array. A count of 0 is the empty array. Both are valid and distinct." },
    { type: "h2", text: "A Minimal Session on the Wire" },
    { type: "p", text: "Here is a complete session: connect, ping, set a key, get it back — fully expanded on the wire level." },
    { type: "code", lang: "text", text: "CLIENT → SERVER\n\n*1\\r\\n              ← Array of 1 element\n$4\\r\\n              ← Bulk string, 4 bytes\nPING\\r\\n            ← \"PING\"\n\n*3\\r\\n              ← Array of 3 elements\n$3\\r\\n              ← Bulk string, 3 bytes\nSET\\r\\n             ← \"SET\"\n$5\\r\\n              ← Bulk string, 5 bytes\nmykey\\r\\n           ← \"mykey\"\n$7\\r\\n              ← Bulk string, 7 bytes\nmyvalue\\r\\n         ← \"myvalue\"\n\n*2\\r\\n              ← Array of 2 elements\n$3\\r\\n              ← Bulk string, 3 bytes\nGET\\r\\n             ← \"GET\"\n$5\\r\\n              ← Bulk string, 5 bytes\nmykey\\r\\n           ← \"mykey\"\n\n\nSERVER → CLIENT\n\n+PONG\\r\\n           ← Simple string\n\n+OK\\r\\n             ← Simple string\n\n$7\\r\\n              ← Bulk string, 7 bytes\nmyvalue\\r\\n         ← \"myvalue\"" },
    { type: "p", text: "The structure is entirely regular. Every message starts with one byte that tells you exactly what you are about to parse. Arrays declare how many elements to expect before you read any. Bulk Strings declare their byte count before the content. There is no ambiguity at any point in the stream." },
    { type: "h2", text: "The Parsing Challenge: Streaming and Partial Reads" },
    { type: "p", text: "The protocol is simple to describe. Parsing it correctly in a production server is harder, for one reason: TCP is a stream." },
    { type: "p", text: "When the server receives bytes from a client, it receives whatever the network delivers — which may be a complete command, a fragment, multiple commands concatenated, or any combination. The parser cannot assume a complete message is available on each read." },
    { type: "p", text: "Consider a client sending a 3-element array command. TCP might deliver it in three separate reads:" },
    { type: "code", lang: "text", text: "Read 1:  *3\\r\\n$3\\r\\nSET\\r\\n$5\\r\\nmy\nRead 2:  key\\r\\n$7\\r\\nmyval\nRead 3:  ue\\r\\n" },
    { type: "p", text: "A naïve parser that expects a complete message on each read would hang or crash. A correct parser must maintain state across reads — remembering where it is in the current message so it can resume when more bytes arrive." },
    { type: "p", text: "This is a state machine problem. At any point, the parser is in one of several states:" },
    { type: "code", lang: "text", text: "WAITING_FOR_TYPE       → read 1 byte, determine message type\nREADING_INLINE         → accumulate bytes until \\r\\n\nREADING_LENGTH         → accumulate digits until \\r\\n, parse as integer\nREADING_BULK_CONTENT   → consume exactly N bytes\nREADING_TERMINATOR     → consume the trailing \\r\\n after bulk content\nCOMMAND_COMPLETE       → dispatch, reset state" },
    { type: "p", text: "A partial read in any state must leave the parser in that state, with bytes already consumed accounted for. When new bytes arrive, the parser resumes from where it left off, not from the beginning." },
    { type: "p", text: "In redis-java, this state machine runs inside Netty's RedisCommandHandler, operating directly on Netty's ByteBuf — an abstraction over raw byte arrays that tracks read and write positions separately and supports zero-copy slice operations. When the handler returns without fully parsing a command, the ByteBuf retains unconsumed bytes for the next read event. No copying. No external buffer management." },
    { type: "h2", text: "Pipelining: Many Commands, One Flush" },
    { type: "p", text: "RESP natively supports pipelining, and understanding how requires understanding what pipelining actually means at the protocol level." },
    { type: "p", text: "Pipelining is not a special mode or protocol extension. It is simply sending multiple commands without waiting for a response to each one." },
    { type: "code", lang: "text", text: "CLIENT → SERVER (all at once, one TCP write)\n\n*1\\r\\n$4\\r\\nPING\\r\\n\n*3\\r\\n$3\\r\\nSET\\r\\n$5\\r\\nkey:1\\r\\n$5\\r\\nval:1\\r\\n\n*3\\r\\n$3\\r\\nSET\\r\\n$5\\r\\nkey:2\\r\\n$5\\r\\nval:2\\r\\n\n*3\\r\\n$3\\r\\nSET\\r\\n$5\\r\\nkey:3\\r\\n$5\\r\\nval:3\\r\\n\n*2\\r\\n$3\\r\\nGET\\r\\n$5\\r\\nkey:1\\r\\n\n\nSERVER → CLIENT (in order, after processing all five)\n\n+PONG\\r\\n\n+OK\\r\\n\n+OK\\r\\n\n+OK\\r\\n\n$5\\r\\nval:1\\r\\n" },
    { type: "p", text: "From the parser's perspective, five pipelined commands look identical to five commands arriving in the same TCP segment. The parser processes them sequentially. The server executes them in order. Responses return in the same order." },
    { type: "p", text: "The performance benefit is eliminating round-trip time. Without pipelining: client sends → server processes → server sends → client receives. With pipelining, the client sends all commands before the server responds to the first. Network latency is paid once for the batch instead of per command." },
    { type: "p", text: "In redis-java, pipelining falls out naturally from the streaming parser. RedisCommandHandler processes bytes in a loop — parse a command, dispatch, continue. If bytes remain after a complete command, the loop continues immediately. Pipelining requires no special handling; it's just consecutive commands in a buffer." },
    { type: "h2", text: "Binary Safety: Why It Matters More Than You Think" },
    { type: "p", text: "One of RESP's most important properties is that Bulk Strings are binary-safe. This is easy to gloss over until you consider what it enables." },
    { type: "p", text: "Because Bulk String content is framed by a length prefix rather than a delimiter, the content can be any sequence of bytes. This means Redis can store:" },
    {
      type: "ul",
      items: [
        "Serialized protobuf or MessagePack payloads",
        "Compressed data with arbitrary byte patterns",
        "Session tokens containing null bytes",
        "Images, audio, or other binary assets",
        "JSON that happens to contain newlines",
      ],
    },
    { type: "p", text: "None of these require escaping, encoding, or transformation before storage. The bytes go in, the bytes come out. The protocol never misinterprets content as framing." },
    { type: "p", text: "This contrasts with Simple Strings, which cannot contain \\r\\n. Use the wrong type for binary content and the parser will misidentify the end of the message, corrupt subsequent commands, and produce confusing errors." },
    { type: "p", text: "The rule is simple: client libraries always encode command arguments as Bulk Strings. Servers never send user data as Simple Strings. Simple Strings are only for fixed, known-safe responses like OK, PONG, and status messages." },
    { type: "h2", text: "Server Response Types: The Contract" },
    { type: "p", text: "The server's response types are a subset of what clients send. A well-behaved server uses each type appropriately:" },
    { type: "code", lang: "text", text: "Command result             RESP type used\n─────────────────────────────────────────\nKey exists, return value   Bulk String\nKey does not exist         Null Bulk String ($-1\\r\\n)\nWrite confirmed            Simple String (+OK\\r\\n)\nNumeric result             Integer (:N\\r\\n)\nList of values             Array of Bulk Strings\nCommand failed             Error (-ERR ...\\r\\n)\nWrong type                 Error (-WRONGTYPE ...\\r\\n)\nBlocked (BLPOP, timeout)   Null Array (*-1\\r\\n)" },
    { type: "p", text: "Client libraries like Jedis and Lettuce are built against these conventions. They call GET, receive either a Bulk String or a Null Bulk String, and return the appropriate nullable type. If a server sends the wrong RESP type — say, a Simple String where a Bulk String is expected — the client may silently misparse or throw a network-looking error." },
    { type: "p", text: "Building a compatible server means knowing not just the RESP types but the specific type each command returns. This is the contract that makes redis-cli, Jedis, Lettuce, and redis-py all speak to redis-java without modification." },
    { type: "h2", text: "The Foundation" },
    { type: "p", text: "RESP is deliberately simple because everything in a Redis server depends on it. The parser runs in the hot path of every client connection. It is the first layer of the event loop, the gateway through which every command must pass before it can be routed, executed, or replicated." },
    { type: "p", text: "In the articles that follow, we will explore how the event loop manages thousands of connections using a single thread, how commands are dispatched after parsing, and eventually how RESP encoding propagates writes across the replication stream. Replication does not define its own wire format — it sends canonicalized RESP commands from master to replicas over a persistent connection, using the same encoding described here." },
    { type: "p", text: "For now, the important thing is to understand what the format looks like byte by byte, why each type exists, and what it costs to parse it incorrectly in a streaming context." },
    { type: "quote", text: "The next article covers the event loop: how Netty handles ten thousand connections using a non-blocking I/O model, and why the threading model matters for everything from command dispatch to replication." },
  ],
}
